---
url: russell.hancox.us
permalink: /articles/:title/
defaults:
  -
    scope:
      path: ""
    values:
      layout: post
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
---
